--- #YAML:1.0
name: Params-Smart
version: 0.04
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: |-
  use both positional and named arguments in a subroutine
license: perl
requires:
  Carp: 0
  Regexp::Common: 1.8
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Params::Smart:
    file: lib/Params/Smart.pm
    version: 0.04
generated_by: Module::Build version 0.2607
